
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"D:\Учеба\магистратура\Технологии и инструменты машинного обучения\ПР№1\не пример\В8\train_images\punching_hole\img_02_425506400_00018.jpg");
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = MLModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
